### ISSUE TITLE
Text wrapping behavior of generate-string has changed

### ISSUE THREAD

**Issue by aviflax** [clj-commons/clj-yaml#1]
I saw that the new version of the library (0.6.0) was published to Clojars, so I thought I’d give it a try.

When I ran my test suite, one of my tests failed because the output of `generate-string` differed slightly from the expected output, which had been generated using the prior version of the library (0.5.6).

My code under test passes a map to `generate-string`; the specific key that’s producing different output is, as EDN:

```edn
{:description "Big-picture diagram showing how our top-level systems and stakeholders interact"}
```

With 0.5.6, when this map is passed to `generate-string` it returns:

```yaml
description: Big-picture diagram showing how our top-level systems and stakeholders interact
```

With 0.6.0 the return value is different:

```yaml
description: Big-picture diagram showing how our top-level systems and stakeholders
  interact
```

It appears that the text has been wrapped. I’m not a YAML expert, but I tested this YAML and apparently that indentation on that last word is one of the (many) ways to break text over multiple lines in a YAML file. These two YAML documents parse identically, but as strings they are definitely not identical.

I took a closer look at the 0.6.0 return value and saw that the line break was inserted at column 84, which seems odd, but then I tried chopping off the key and measuring just the value; in this case the line break was inserted at column 71, and without the line break the line would be 80 chars long, which is not shocking as wrapping at 79 is a thing.

My speculation would be that this is due to the upgrade of SnakeYAML from 1.13 to 1.23.

If that turns out to be correct, then I’d like to suggest that we should consider trying to change the options that `generate-string` passes to SnakeYAML so as to restore the prior default behavior of `generate-string` which IMHO it is better not to change. (Introducing new options is generally cool, but changing defaults — not great.)

I don’t have time to continue debugging this right now, but I might be able to find some time next week if no one else can in the meantime. And either way I’d be happy to try to help out with a fix, if and when one is needed+desired.

Many thanks to the maintainers for keeping this project alive!

**Comment by marcomorain** [comment]
@aviflax it might be that the old behaviour is still available through the DumperOptions - https://static.javadoc.io/org.yaml/snakeyaml/1.23/org/yaml/snakeyaml/DumperOptions.html

**Comment by aviflax** [comment]
@marcomorain yup, you were right, it is. I tested locally and confirmed. So I’ve opened #2 to restore the prior behavior.
