### ISSUE TITLE
Upgrade to SnakeYAML 1.41 and solve "Number of aliases exceeds" error

### ISSUE THREAD

**Issue by arichiardi** [clj-commons/clj-yaml#100]
Hi there, I have run into this problem when my Yaml contains too many aliases

`Number of aliases for non-scalar nodes exceeds the specified max=50`

Apparently the limit is now customizable with properties in [SnakeYAML version 1.41](https://github.com/jenkinsci/configuration-as-code-plugin/issues/1374). 

I wonder if we could bump the dependency to it?

**Comment by lread** [comment]
Hi @arichiardi, thanks for raising an issue.

I don't know of a SnakeYAML v1.41.

But what you are looking for [seems to exist in the current 1.x version which is 1.33](https://javadoc.io/static/org.yaml/snakeyaml/1.33/org/yaml/snakeyaml/LoaderOptions.html#setMaxAliasesForCollections-int-).

As of this writing, clj-yaml uses SnakeYAML 1.33.

And clj-yaml already supports setting this value, see `:max-aliases-for-collections` docstring for [parse-string](https://cljdoc.org/d/clj-commons/clj-yaml/1.0.26/api/clj-yaml.core#parse-string)

Let us know if this does the trick for you.

**Comment by arichiardi** [comment]
> I don't know of a SnakeYAML v1.41.

Duh I completely misread that issue!

Thanks for pointing this out and sorry for the noise, I am closing this cause it make little sense as it is 👍

**Comment by lread** [comment]
No problemo, @arichiardi! Glad you are sorted out.
