### ISSUE TITLE
Incorrectly identifies a map key as a keyword literal

### ISSUE THREAD

**Issue by peristeri** [clj-commons/clj-yaml#102]
The key on the map falsly identified as a literal and convert it automatically
The simple example is: `(yaml/parse-string "on: [pull]") ;; => #ordered/map ([true ("pull")])`

While what I expect is`(yaml/parse-string "on: [pull]") ;; => #ordered/map ([:on ("pull")])`

**Comment by lread** [comment]
Hi @peristeri, thanks for raising an issue.

As surprising as it may seem, in YAML 1.1 `on` is equivalent to true.
Here's the relevant portion of the spec: https://yaml.org/type/bool.html

This changed in YAML 1.2, but clj-yaml wraps SnakeYAML which is a YAML 1.1 processor.

In YAML 1.1 to treat `on` as literal:
```Clojure
user=> (yaml/parse-string "'on': [pull]")
#ordered/map ([:on ("pull")])
```

**Comment by peristeri** [comment]
Cool, I assumed that clj-yaml was working with the version 1.2 processor. I'll close this issue and find a work around.

Thanks for the quick response.
