### ISSUE TITLE
Make it easier for folks to include clj-yaml in a GraalVM native image

### ISSUE THREAD

**Issue by lread** [clj-commons/clj-yaml#104]
SnakeYAML, and therefore clj-yaml, needs some config/options specified to work successfully with GraalVM native-image.

This config can be specified in a lib in such a way it will automatically be picked up by GraalVM `native-image`.

Here's an example of [such a config from babashka](https://github.com/babashka/babashka/blob/master/resources/META-INF/native-image/babashka/babashka/native-image.properties).

This work implies adding native-image tests on CI.

Currently known to be needed is:
```
     --initialize-at-build-time=org.yaml.snakeyaml
```

**Comment by borkdude** [comment]
Yep, let's add such a config.
