### ISSUE TITLE
Please make a release for 0.7.0 (git tag)

### ISSUE THREAD

**Issue by baldurmen** [clj-commons/clj-yaml#12]
Hi!

I'm planning on packaging this program in Debian and it would be much appreciated if you could tag the 0.7.0 version (d2325668f49b86cd3b92738cf668f8910d3c7135) in git as such :)

**Comment by slipset** [comment]
@baldurmen Is https://github.com/clj-commons/clj-yaml/tags what you need? If so, please close this issue, if not please elaborate :)

**Comment by baldurmen** [comment]
Yes, thanks a lot.
