### ISSUE TITLE
ci chore: vulnerability scan is failing after 6h

### ISSUE THREAD

**Issue by lread** [clj-commons/clj-yaml#125]

**Comment by damu9618** [comment]
@lread Thanks for the input, However I have https://github.com/jeremylong/DependencyCheck/issues/6760 this issue post upgrade to depdendencycheck v10

**Comment by lread** [comment]
Thanks, @damu9618. I noticed that. I'm not clear on the root cause yet. Is it not that the NIST data feeds are misbehaving these days? I was guessing that bumping to DependencyCheck latest (v10) would not hurt my situation, but I could be wrong.
