### ISSUE TITLE
Consider Upgrading to SnakeYAML 2.3

### ISSUE THREAD

**Issue by lread** [clj-commons/clj-yaml#134]
SnakeYAML 2.3 was just released (August 31, 2024)

Maven central: https://central.sonatype.com/artifact/org.yaml/snakeyaml/2.3

Changelog: https://bitbucket.org/snakeyaml/snakeyaml/wiki/Changes

If nobody else beats me to it, I can take a peek to:
- learn if clj-yaml works with this new version
- review changes to learn about any issues/opportunities for clj-yaml
- if all good, consider upgrading to the new version (with the understanding that clj-yaml is a babashka built-in)

Historically, there have sometimes been adjustments after a SnakeYAML release.
So, should we want/need to upgrade, we might want to wait a couple of weeks to see if anything pops up.

**Comment by lread** [comment]
CI Results are in. All tests pass, and generated test native image consistently gained about 12kb.

Using Clojure 1.12

|OS       | Graal 22 flavor | Image size with 2.3 | Image size with 2.1 | Difference     |
|---------|-----------------|---------------------|---------------------|----------------|
| Linux   | Oracle          | 37,224,888 bytes    | 37,212,600 bytes    | + 12,228 bytes |
| Linux   | Community       | 46,280,728 bytes    | 46,268,440 bytes    | + 12,228 bytes |
| Windows | Oracle          | 32,604,160 bytes    | 32,591,872 bytes    | + 12,228 bytes |
| Windows | Community       | 41,095,168 bytes    | 41,082,880 bytes    | + 12,228 bytes |

@borkdude, I'm tempted to merge the SnakeYAML bump just to get it on master (and potentially "out there" a bit more).

Do you have any concerns?

**Comment by borkdude** [comment]
LGTM!

**Comment by lread** [comment]
@borkdude, have I told you how easy you are to work with lately?
Always such a pleasure!
