### ISSUE TITLE
Support namespaced keywords

### ISSUE THREAD

**Issue by skuro** [clj-commons/clj-yaml#16]
Currently, encoding of keywords strips away the namespace:

```clojure
user> (yaml/encode {:one/two 42})
;; => {"two" 42}
```

I discovered this while round-tripping (`yaml/parse-string` + `yaml/generate-string`) a Kubernetes YAML, which included something like:

```yaml
nodeSelector:
    cloud.google.com/gke-nodepool: custom-pool
```

I fixed it locally with

```
(extend-type clojure.lang.Keyword
  yaml/YAMLCodec
  (encode [data] (let [n (namespace data)
                       v (name data)]
                   (cond->> v
                     (some? n) (str n "/")))))
```

**Comment by borkdude** [comment]
I think this library should support this (by default) and consider this a bug. What do you think @slipset @marcomorain ?

**Comment by slipset** [comment]
I generally defer to @marcomorain for these kinds of questions, but it seems reasonable to me. @skuro would you be interested in whipping up a PR?

**Comment by skuro** [comment]
Opened #17 which uses a slightly optimized approach to the same result:

```clojure
  clojure.lang.Keyword
  (encode [data]
    ;; using clojure.core/name would drop the namespace
    (subs (str data) 1))
```

Hail hail the [anti-if campaign](https://francescocirillo.com/pages/anti-if-campaign)!
