### ISSUE TITLE
Doesn't it yet have the ability to add arbitrary tags?

### ISSUE THREAD

**Issue by kbaba1001** [clj-commons/clj-yaml#23]
I tried using [tags](http://yaml.org/spec/1.1/current.html#id858600) like next, but I got an error.

```clojure
(require '[clj-yaml.core :as yaml])
(yaml/parse-string "
- name: !foo Mary Smith
")
```

error:

```
Execution error (ConstructorException) at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructUndefined/construct (SafeConstructor.java:539).
could not determine a constructor for the tag !foo
 in 'string', line 2, column 9:
    - name: !foo Mary Smith
```

I read the source code, I found the TODO comment:
https://github.com/clj-commons/clj-yaml/blob/master/src/clojure/clj_yaml/core.clj#L59

Does this comment mean that it doesn't yet have the ability to add arbitrary tags?

**Comment by The-Alchemist** [comment]
I think  `clj-yaml` doesn't expose the `setSkipMissingProperties()` method of snakeyaml. See https://stackoverflow.com/a/30162482/423943

That's OK, you might be able to call it manually (haven't checked the code), or you might be able to just create a class called `foo` using `deftype`.

Better question for https://ask.clojure.org/ :)

[0]: https://stackoverflow.com/a/30162482/423943

**Comment by borkdude** [comment]
clj-yaml should probably support this. Feel free to make proposals, starting with a clear problem statement and with several alternatives.

**Comment by borkdude** [comment]
@grzm This issue is related to your request. PassthroughConstructor should also help.
