### ISSUE TITLE
Parsing problem when "/" in yaml key

### ISSUE THREAD

**Issue by jerneyio** [clj-commons/clj-yaml#26]
I'm trying to parse a document type ([RAML](https://raml.org/)) that uses "/" in certain keys:

```clojure
(require '[clj-yaml.core :as yml])

(yml/parse-string "application/json:\n  data")
```

This returns: `#:application{:json "data"}`, but I was expecting something like this: `{:application/json "data"}`. Is there a way I can accommodate these "/" chars in the keys without using `:keywords false`?

**Comment by borkdude** [comment]
@jerneyio This is just the way Clojure prints maps with namespaced keys. Try `(set! *print-namespace-maps* false)` to change this.

**Comment by jerneyio** [comment]
Thank you for the suggestion, I'm still learning!
