### ISSUE TITLE
Add an option to parse-string that maps YAML sequences to Clojure vectors instead of Clojure LazySeqs

### ISSUE THREAD

**Issue by bombaywalla** [clj-commons/clj-yaml#29]
It would be useful to have `parse-string` return a Clojure Vector rather than a Clojure LazySeq for YAML sequences.
It would allow the use of `get-in` on the resultant Clojure data structure.
`io.forward/yaml` does this.

**Comment by borkdude** [comment]
This has come up before here: https://github.com/clj-commons/clj-yaml/pull/18
The reason why this wasn't done was to support recursive YAML (which arguably is a niche case).

**Comment by bombaywalla** [comment]
Sorry.  I should have checked closed issues before creating a new one.
I'll use the postwalk suggestion mentioned in the previous issue.
Closing this issue.
