### ISSUE TITLE
Add parse-stream call

### ISSUE THREAD

**Issue by Deraen** [clj-commons/clj-yaml#3]
Before commit https://github.com/clj-commons/clj-yaml/commit/1cdc4a362536c1a05ec045389f8a8ac8d1e293d3 `parse-string` used to work with `InputStream` thanks to reflection. Now, `parse-string` only works with `String`, which makes sense.

I think it would be good idea to add `parse-stream`, similar to  `parse-string` but with `InputStream` type hint.

And related to this, in addition to `generate-string`, `generate-stream` taking a `writer` would be useful.

I just inlined these version to Muuntaja for now: https://github.com/metosin/muuntaja/pull/94/files

**Comment by slipset** [comment]
I guess a PR would be welcome?
