### ISSUE TITLE
Clojars shows 1.0.11 as latest, but project.clj still lists 1.0.11-SNAPSHOT

### ISSUE THREAD

**Issue by rbrw** [clj-commons/clj-yaml#32]
Clojars claims 1.0.11 exists https://clojars.org/io.forward/yaml but the current project.clj specifies 1.0.11-SNAPSHOT.  I wondered if 45f3c9cc5e25a8b969da4a2b327211b72c50fd9d might have meant to change it to 1.0.12-SNAPSHOT.

Thanks

**Comment by borkdude** [comment]
This is a about a different yaml library, not clj-commons/clj-yaml
