### ISSUE TITLE
What is the public API?

### ISSUE THREAD

**Issue by lread** [clj-commons/clj-yaml#66]
When doing a pass of the source (#65), I sometimes get confused as to what the intended public API of an adopted lib is. This is the case for me for clj-yaml.

I find a library much easier to support and maintain when it has a clear public API.
It reduces the surface of what we need to be careful not to break and gives us the freedom to change what is clearly internal.

## Clearly public:
- parse-stream
- parse-string
- generate-stream
- generate-string
- unmark - to support reading parsed marked (with positional data) yaml

## Probably public:
- marked? - maybe needed (or useful?) to support reading marked yaml? 

## Looks internal to me:
- flow-styles
- default-dumper-options
- make-dumper-options
- default-loader-options
- make-loader-options
- make-yaml
- YAMLCodec (encode, decode)
- mark - I think this is only needed to mark marked yaml

## Confirmations from the wild
I looks like a similar public API [is exposed by babashka](https://github.com/babashka/babashka/blob/c94960eac180731ae0e8e0f78f1326961c51a916/feature-yaml/babashka/impl/yaml.clj#L9-L14).

## Exceptions in the wild
I've not done an exhaustive search but with grep.app I have found:
- kvert is using [what I guessed was internal](https://github.com/mcorbin/kvert/blob/7c5bf00cc70949712c2810cae8fb67bda9baa851/src/kvert/commands/edn.clj#L6-L25). It extends the `YAMLCodec`, makes use of `make-yaml`, `decode` (we just effectively broke this API with our recent unknown tag support).
- I think we also broke [muuntaja](https://github.com/metosin/muuntaja/blob/83f7f707b69b3111668856804733c4fd17373159/modules/muuntaja-yaml/src/muuntaja/format/yaml.clj#L14-L27) with our `decode` signature change. They use `encode`, `decode`, `makeyaml`. 
- [swarmpit](https://github.com/swarmpit/swarmpit/blob/91ae05014c0d9e0355e5c457a1e6b309badd0e37/src/cljc/swarmpit/yaml.cljc#L10-L24) also uses `YAMLCodec`, `encode`, and even `flow-styles`. 

It's my perception that the above libs were overcoming shortcomings in clj-yaml. 
Am I right?

Since clj-yaml did not delineate public from private vars, users rightly assumed all was public. 

We clearly assumed the `YAMLCodec` is internal with our recent changes.
Should it be? I dunno. Please share what you think.

## Option 1 - there is no private API
Leave things as they are.
But any new private implementation must be private.

## Option 2 - doc-break only
Be clear about our public API but through `:no-doc` meta only.
We'd be clearer but not really affecting much usage change.

## Option 3 - move forward with a reasonable public API
Move what we deem internal to impl ns(es). 
A breaking change for some and would negatively affect some folks on upgrade.
They could still choose to use unsupported undocumented impl nses, but with the understanding of what that means.
Might encourage folks to contribute back to clj-yaml when the public API does not meet their needs.

## Proposal
Not sure. Initial feeling is Option 3. But I'd need to understand if my guesses about public vs private are correct.

**Comment by borkdude** [comment]
> Be clear about our public API but through :no-doc meta only.

If we would mark those with no-doc we could give ourselves the permission to break those in future releases since we assume nobody relies on those, which isn't a good assumption since there are counter-examples from the wild, yes?

**Comment by lread** [comment]
Yes, Option 2 is a softer doc-only version of Option 3 which is, potentially (depending on what we decide is public) a deliberate  clj-yaml user breaking change. A very un-clojury thing to do. If only we could rewrite history, eh?

We could do a thorough search and make our public API everything we see being used in the visible wild. Private repos could still be affected. I took this approach for etaoin which also did not distinguish public from internal.
This would include trying to adapt our recent `decode` change to be an unbreaking change.

Option 1 would be the safest bet for clj-yaml users but leaves us with maybe a bit of an odd public API. And one that is more challenging to support. But at least we'd have an understanding that we shouldn't break it.

**Comment by lread** [comment]
I pondered option 4 - deprecate clj-yaml and create clj-yaml2 (if the burden of other options is not palatable). But I think that's not a very good option for babashka, which has clj-yaml baked in.

**Comment by lread** [comment]
Maybe Option 1 is the way to go?

**Comment by lread** [comment]
Yeah, gonna assume Option 1, pipe in if you have other strong opinions.

**Comment by borkdude** [comment]
I would say option 1 but going forward: be very strict about what to expose.

**Comment by lread** [comment]
Agreed
