### ISSUE TITLE
Deprecated constructor `org.yaml.snakeyaml.representer.Representer`

### ISSUE THREAD

**Issue by vemv** [clj-commons/clj-yaml#76]
https://www.javadoc.io/doc/org.yaml/snakeyaml/latest/org/yaml/snakeyaml/representer/Representer.html#Representer--

Hope it helps!

**Comment by lread** [comment]
Thanks @vemv, I did catch #61 because I turned on javac linting, but missed this one.
Did you use Eastwood to find this one?

**Comment by lread** [comment]
Cool, much thanks, I'll add Eastwood linting as well then!

**Comment by vemv** [comment]
Cool, happy to hear! I often run clj-kondo first, possibly short-circuiting the E step.
