### ISSUE TITLE
support nesting-depth-limit on Yaml-options

### ISSUE THREAD

**Issue by neeasade** [clj-commons/clj-yaml#81]
from https://github.com/snakeyaml/snakeyaml/blob/ebad791333afee13bfd48fd9cf1ff6dab5faa51a/src/main/java/org/yaml/snakeyaml/LoaderOptions.java#L130

**Comment by borkdude** [comment]
PR welcome

**Comment by lread** [comment]
Closed by b560a8c9ccadd887183140f11ee2e7658f463aa7
