### ISSUE TITLE
Consider bumping org.flatland.ordered

### ISSUE THREAD

**Issue by lread** [clj-commons/clj-yaml#93]
I just noticed we are using `org.flatland/ordered` 1.5.9 when [1.15.10 is available](https://github.com/clj-commons/ordered/blob/master/CHANGELOG.md#11510---2021-10-09).

I typically bump deps to the current version during a maintenance pass - unless there are obvious issues.

Any reason we don't want to do that? Tests pass with 1.15.10.

**Comment by lread** [comment]
Closed by #97

**Comment by borkdude** [comment]
Oh I didn't even notice you had an issue for this

**Comment by lread** [comment]
Ha!
