### ISSUE TITLE
The incoming YAML document exceeds the limit: 3145728 code points.

### ISSUE THREAD

**Issue by kwladyka** [clj-commons/clj-yaml#94]
When read large YAML

```
The incoming YAML document exceeds the limit: 3145728 code points.
```

the `code_point_limit` is needed to overwrite, but I didn’t find a way to do this with clj-yaml.

How do you read large YAML files?

From slack #clj-yaml

> There isn't currently an option, but you can call make-loader followed by (.setCodePointLimit ...) on it.
But I don't see where you can then pass that loader. That should probably be added as well, along with an explicit option for the :code-point-limit

**Comment by PetrGlad** [comment]
I have a large file, loaded as
```
(def all-of-it (yaml/parse-stream (javaio/reader "a-file.yaml") :load-all true))
```
Curiously, when I evaluate it in a REPL, this one raises the exception `(map identity all-of-it)`, but this one does not `(take 1000000 all-of-it)` does not (the limit is larger than the number of documents in the input file).

**Comment by borkdude** [comment]
@PetrGlad Can you wrap that take in a `doall`?

**Comment by PetrGlad** [comment]
Sorry, it looks like a reproduction includes to attempt an operation on the sequence first, then other operations succeed. Like
```clojure
(def all-of-it (yaml/parse-stream (javaio/reader "a-file.yaml") :load-all true))
(map identity all-cases) ; <-- FAILS
(map identity all-cases) ; <-- OK
```

**Comment by borkdude** [comment]
If anyone wants to do a PR, we're open to that. It should be relatively straightforward to add:

- an option to the size
- an option to work with a pre-defined loader

**Comment by PetrGlad** [comment]
Just wanted to note that the actual problem (in my case) is in the snakeyaml. I have already reported that.
Snakeyaml have enforced the input size limit, but it actually limits the whole input stream size, while it only makes sense to limit document size instead. For example this makes difference when input stream contains many small documents.
Making the limit configurable would be a workaround, nonetheless.

**Comment by PetrGlad** [comment]
Yes, that was the change.
I sent a message to google groups because other services were locked down due to attacks. 
They admitted that it is likely a problem but I do not know if a ticket was created ([here](https://groups.google.com/g/snakeyaml-core/c/q3Yi6oNc2JI)).
